add j() - Jump around anywhere

diff --git a/home/.bash/functions-cd b/home/.bash/functions-cd
--- a/home/.bash/functions-cd
+++ b/home/.bash/functions-cd
@@ -5,7 +5,7 @@
 # http://www.commandlinefu.com/commands/view/11246/bashksh-function-given-a-file-cd-to-the-directory-it-lives
 cdf() {
 	[ $# -ge 1 ] || {
-		echo "Usage: $FUNCNAME filename">&2
+		echo "Usage: $FUNCNAME filename" >&2
 		return 1
 	}
 
@@ -15,7 +15,7 @@ cdf() {
 # http://www.commandlinefu.com/commands/view/13604/change-directory-for-current-path-in-bash
 cdd() {
 	[ $# -ge 2 ] || {
-		echo "Usage: $FUNCNAME old_dir new_dir">&2
+		echo "Usage: $FUNCNAME old_dir new_dir" >&2
 		return 1
 	}
 
@@ -25,7 +25,7 @@ cdd() {
 # http://www.commandlinefu.com/commands/view/12669/create-a-directory-and-change-into-it-at-the-same-time
 mkcd() {
 	[ $# -eq 1 ] || {
-		echo "Usage: $FUNCNAME dirname">&2
+		echo "Usage: $FUNCNAME dirname" >&2
 		return 1
 	}
 
@@ -89,6 +89,97 @@ cd() {
 		;;
 	*)	echo "${0##*/}: $FUNCNAME: usage: $FUNCNAME [-LP] [dir] [change]" >&2
 		return 2 ;;
+	esac
+}
+
+# =========================================================================
+
+# Jump around anywhere
+# - Keep the list of most frequently visited directories
+# - Allow to jump to the directories fastly by aliases
+j() {
+	if [ $# -eq 0 ]
+	then
+		cat - <<HELP
+Jump around anywhere
+  j    ALIAS [SUBDIR] Jump to the directory by its alias
+  j -l ALIAS [SUBDIR] List the directory content
+  j -a ALIAS          Create the alias for the current directory
+  j -d ALIAS          Delete the alias
+  j -A                Display all directories and their aliases
+HELP
+		return
+	fi
+
+	local CONF=~/.jconf
+
+	if [ ! -f "$CONF" ]
+	then
+		echo "File not exist: ~/.jconf" >&2
+	fi
+
+	local jcmd="cd"
+
+	local opt
+	while getopts ":la:d:A" opt
+	do
+		case "$opt" in
+		l )
+			jcmd="ls"
+			break
+			;;
+		a )
+			if [ -f "$CONF" ] && grep -Pq "^$OPTARG\t" "$CONF"
+			then
+				echo "Entry already exists: $OPTARG" >&2
+				return 255
+			fi
+			printf '%s\t%s\n' "$OPTARG" "$PWD" >>"$CONF"
+			return $?
+			;;
+		d )
+			sed -i "/^$OPTARG\t/d" "$CONF"
+			return $?
+			;;
+		A )
+			sort "$CONF"
+			return $?
+			;;
+		: )
+			echo "Alias required" >&2
+			return 255
+			;;
+		\? )
+			echo "Bad option: $OPTARG"
+			return 255
+			;;
+		esac
+	done
+
+	shift $(( OPTIND - 1 ))
+
+	if [ -z "$1" ]
+	then
+		echo "Alias not specified" >&2
+		return $?
+	fi
+
+	local -a jdir
+	mapfile -t jdir < <( sed -n "s/^$1\t*//p" "$CONF" )
+
+	case "${#jdir[@]}" in
+	0 )
+		echo "No entry found: $1" >&2
+		return 255
+		;;
+	1 )
+		# cd or ls
+		$jcmd "${jdir[0]}/$2"
+		;;
+	* )
+		echo "More than one entry found: $1" >&2
+		return 255
+		;;
 	esac
 }
 
